- src/iop/channelmixerrgb.c
I've just moved the warning label above the notebook and the calibration expander below it. I assume that's how you'd want it, but let me know otherwise and I'll change.
Also right aligned the buttons. Shall I split the result label, so the numbers can be right aligned and any ellipsizing is in the static text so that the number remain readable?
At the moment, the expander closes each time one changes images or history point (gui_update). Is that what you want or do you want it to stay open (maybe even across restarts)?
> place color checker calibration outside notebook

- src/external/LibRaw-cmake/CMakeLists.txt
This PR brings in the LibRaw 0.21-Beta1 from the main darktable project, which supports Canon R7 CR3 files, and cherry-picks also the corresponding OpenMP fix.
> Update LibRaw to add support for Canon R7 CR3 files

- .github/workflows/lin-nightly.yml
Ubuntu 20.04 used in CI to build AppImage has a lower version of exiv2 which does not support CR3 files, but AppImage is expected to work on most system with most features. This commit fetch and build exiv2 0.27 from source instead of Ubuntu repo, so the final AppImage will link against and bundle new version of exiv2.
Fixes <https://github.com/aurelienpierreeng/ansel/issues/72>.
> Manually build and install newer exiv2 in CI

- .ci/ci-script-appimage.sh
- .github/workflows/lin-nightly.yml
linuxdeploy tries to resolve all linked libraries and collect them,
however, we don't link plugins, but load them with `dlopen()`, so
linuxdeploy cannot see them and resolve their dependencies.
This commit tells linuxdeploy the plugin dir so it will resolve and
collect dependencies of plugins.
Fixes <https://github.com/aurelienpierreeng/ansel/issues/54>.
This PR also enable `lensfun-update-data` because it works now.
This PR also make nightly Linux build checkout triggered branch, instead of master.
> Fix lensfun in AppImage (and other plugin dependencies)

- src/iop/negadoctor.c
A small bug correction for my first PR:
On the first panel of Negadoctor module, there is a bug where one cannot deactivate the color picker of the "scan exposure bias" parameter.
After reading the code, I noticed that line `868` initialize the color picker while the color picker was already initialized at line `866`.
Deleting that line corrects the issue and doesn't affect the use of the module on my side.
> Negadoctor: remove an extra line

- src/iop/negadoctor.c
**What this is about:**
In Negadoctor, picking sample in the picture to set white balance is very handy.
But sometimes the calculated ratio is not pleasant or there is nowhere to pick sample in the picture because no neutral surface is visible in the picture, so we need to fix white balance by hand.
Moreover, the color picker does an automatic adjustment to put the maximum value for shadows and minimum value for highlights to 1 while keeping the same ratio.
When adjusting the values by hand, we have to do that adjustment by hand too !
(by setting each channel to `value / maximum or minimum value`).
**What this does:**
After modifying settings by hand, clicking the button "Normalize" does the same adjustment automatically.
> Add "Normalize" button in Negadoctor

- src/iop/colorbalancergb.c
Proposed change for issue #51 with a 0.75× scaling on all 4-way chroma sliders max value. The range is still quite large, but it is a little more under control than before.
Global chroma and power chroma could both come even lower but I think that can be left up for discussion.
> [Issue #51] Rescale 4-way chroma slides by 0.75

- src/common/exif.cc
- tools/basecurve/exif-wrapper.cpp
Just backport patch from Arch Linux repo.
See <https://gitlab.archlinux.org/archlinux/packaging/packages/darktable/-/blob/3e9be4c8e72e5a99d37b9cdb2119e3e0d8469d9d/exiv2-0.28.patch>.
I already tested this on my system with both exiv2 0.27 and exiv2 0.28, user may needs a rebuild but it works fine.
> Support exiv2 0.28 API change

- src/iop/highlights.c
Discretely set maximum iterations number to 512 instead of 256. You'll have to right-clic and type a number greater than 256.
fix #133
In some cases, one still have magenta in the corrected area even if the iterations number is set to the current maximum (256 iterations).
This change could help those situations. (need more test)
> Increase Highlight Correction's max laplacian iterations

- src/develop/lightroom.c
It fix #181. `xmlParseEntity()` is remplaced by `xmlReadFile(,,)` .
Works on windows 11 and Ubuntu 22.04.
> Fix libxmp2 deprecated function

- data/kernels/filmic.cl
- src/iop/filmicrgb.c
This PR fixes two issues in Filmic RGB's `process_cl()` function, one of them being major depending on the user's hardware platform.
The first one makes the filter yield a black image on Intel Arc GPUs (at least the A770 on my system, on Linux with `intel-compute-runtime` 23.13.26032.30).  The reason is that, when the filmic mask kernel is called, `clipped` is passed as a `cl_mem` (a pointer type), whereas it is a `uint16_t`.  The first commit fixes this.  (It might be worth to switch to a more type-safe API here--it looks like DT did so.)
The second issue is that `clipped` is not free'd on OpenCL errors, and that the copy operation from the device to the host is not checked for errors.  The second patch fixes this.
I also want to report that, otherwise, Ansel seems to work fine with …
> Fix Filmic RGB on Intel Arc

- src/common/exif.cc
- src/common/image.c
- src/common/image.h
- src/common/imageio.c
- src/common/mipmap_cache.c
- src/control/jobs/control_jobs.c
- src/develop/develop.c
- src/develop/lightroom.c
- src/dtgtk/thumbnail.c
- src/dtgtk/thumbtable.c
- src/imageio/format/copy.c
- src/imageio/storage/disk.c
- src/imageio/storage/example.c
- src/imageio/storage/gallery.c
- src/iop/colorin.c
- src/iop/watermark.c
- src/libs/metadata_view.c
- src/libs/tools/image_infos.c
- src/lua/image.c
- src/lua/luastorage.c
- src/views/darkroom.c
- src/views/map.c
- src/views/print.c
The state of all masks used by a module is saved for each history entry for modules using masking. After 100 history steps using 20 masks, that's 2000 copies of mask nodes to read/write from/to database and XMP, resulting in slow-downs of ~30 s each time a module parameter is changed.
The real solution would be to maintain a separate history for masks, instead of having a full snapshot of them in the module history. But properly linking mask history to module history will be some work. In any case, the current design is terrible.
For now, we only count the number of masks × history steps, and display a warning when it's > 250 (the value is completely arbitrary).
> Warn user when too many masks × too many history steps are going to be written in DB/XMP

- src/bauhaus/bauhaus.c
When format of a slider is set to percentage, it will decrease 2 digits and set factor to 100, so when we set normalized value of the slider, we need to handle both digits and factor.
In the large refator of commit 48a86a9c0353f87444fd6956f087af933ecad599, we forget to multiply factor while setting normalized value, this makes percentage sliders always get floored to integer value and lose the float value.
This commit fixes it by multiplying factor while setting normalized value.
> Bauhaus: Fix wrongly floored value of percentage sliders

- src/CMakeLists.txt
libavif released their first stable version, but its `config-version.cmake` requires major version to be exactly matched, to support libavif >= 0.8.2, we have to check version manually.
I tested on my system that Ansel could built with libavif 1.0.1, and this does not break building with libavif 0.11.1 on CI.
> CMake: Manually check version to support libavif 1.0.0

- data/ansel.desktop.in
The icon path in ansel.desktop doesn't point to Ansel's icon folder / file and the program doesn't show the Ansel's icon.
`Icon=ansel`
It points no to ansel.svg in Ansel's program folder so the system find what icon to use.
`Icon=${CMAKE_INSTALL_PREFIX}/share/icons/hicolor/scalable/apps/ansel.svg`
> ansel.desktop : Complete path to icon

- src/common/debug.h
- src/develop/blend_gui.c
- src/develop/develop.c
- src/develop/develop.h
- src/develop/imageop.c
- src/develop/masks/masks.c
- src/gui/actions/display.h
- src/gui/color_picker_proxy.c
- src/iop/ashift.c
- src/iop/basicadj.c
- src/iop/channelmixerrgb.c
- src/iop/crop.c
- src/iop/demosaic.c
- src/iop/filmicrgb.c
- src/iop/highlights.c
- src/iop/retouch.c
- src/iop/rgblevels.c
- src/iop/toneequal.c
- src/libs/duplicate.c
- src/libs/history.c
- src/libs/navigation.c
- src/libs/snapshots.c
- src/views/darkroom.c
Provide a single way to trace a function without modify all callers.
> Add DT_DEBUG_TRACE_WRAPPER() and use it to unify trace debug helpers

- src/imageio/format/CMakeLists.txt
If you read too much CMake, you need to have a break, otherwise you are very likely to make mistakes. Use the correct variable to fix it.
> CMake: Fix build check on AVIF exporter

- data/anselconfig.xml.in
- src/gui/gtkentry.c
This PR corrects the default file patterns:
- `$(FILEFOLDER)` was used instead of `$(FILE.FOLDER)`
- Other variables use a valid form but doesn't correspond to the auto-completion's patterns which is supposed to show good practice. (`.` is used to separate words in auto-completion, instead of a `_` in the default patterns)
> Update the default patterns in anselconfig

- src/common/import.c
Some scanners produce BMP images and we should allow user to import BMP.
> import: Allow BMP files

- packaging/macosx/1_install_hb_dependencies.sh
- tools/basecurve/CMakeLists.txt
Solving the issue caused by Exiv2 version 0.28.x during compiling /tools/basecurve (do we still need that tool?) with Apple clang. Solution copied from darktable by changing c++ standard to 17.
> Enable Exiv2 0.28.x compilation. Solving issue #8

- src/common/import.c
- src/common/utility.c
- src/control/jobs/control_jobs.c
- control_jobs.c : removed redundant path formatting code for windows.
- utility.c : removed a path validity test for windows in a function that was only normalizing.
- import.c : cut the beginning of base directory path AFTER decoding pattern to satisfy win normalization.
> Import: fix issues on win

- src/common/image.c
- src/common/import.c
**Database:**
in the Import file chooser, there can be a crash when selecting a file which have been copied earlier and the copy have then been removed from database.
The entry in the `meta_data` table was still existing and was used to recover an `imgid` and tried to find a path even if the file was deleted.
To fix this, when removing an image, now it deletes the image's entry in `meta_data` table too.
**Import preview:**
The function to refresh preview now uses the list of selected file instead of the selected file from file chooser, to find if a file is in the library by metadata.
> Import and remove from database fixes

- src/common/collection.c
- src/control/control.c
- src/control/control.h
- src/gui/actions/file.h
Activated import in global menu from darkroom.
**changed the switching process after import :**
- Added a function to "reload" a view. This just switch
view to `lighttable` then to the desired view.
After import process:
- `darkroom` is loaded if 1 image has been imported.
If the current view is `darkroom`, it reloads the view using the new reload function. Because the collection and image's focus changed onto a different image, the `darkroom` reloads with a different image;
- `lighttable` is loaded if more images have been imported, excepted if the current view is `lighttable`;
> "Import end" behavior from darkroom.

- doc/CMakeLists.txt
The ansel-git archlinux package doesn't build anymore. It fails at make install.
It seems it's following the removal of README.md and TRANSLATORS.md from 38c9b5108273aeda6fd7f5427504ec5a0ed77f72
This PR should fix this
> Fix make install following 38c9b5108273aeda6fd7f5427504ec5a0ed77f72

- src/common/guided_filter.c
- src/iop/hazeremoval.c
Hi,
I want to preface this by saying that I am not very familiar with DT/Ansel's codebase, nor OpenCL.
With that out of the way, the first commit seems to fix issue #369, by replacing all `sizeof(variable)` by `sizeof(type)`, and by adding a third dimension to the kernel sizes, like almost all other OpenCL pathes in the codebase.  I don't know what the exact mechanisms behind this issue are, but I no longer have artifacts as described in #369 with this patch.
The second commit is a preemptive attempt to prevent the same kind of issue in the haze removal module.
Best regards.
> Harmonise OpenCL invokations in the guided filter and the haze removal module

- src/develop/pixelpipe_hb.c
pixelpipe_get_histogram_backbuf() can be called with `piece` set to NULL, which can lead to crashes under some conditions (e.g. when the crop filter is active) as it is directly dereferenced without checking its validity.  Such a crash is mentioned in issue #357.
This PR adds a null pointer check before dereferencing `piece`, making the function return early if it is not successful.
> pixelpipe: check if `piece' is null to avoid crashes

- src/libs/histogram.c
Vector scope is always zooming out due to the fact `delta_y` is not initialized (or initialized with garbage) and the return of `dt_gui_get_scroll_unit_deltas()` is not handled properly causing `new_value` to always increase.
> Vectorscope: fix infinite scroll due to mishandled event

- src/libs/histogram.c
Fixes crash caused by scroll on Scopes panel after the user clicks on reset button.
> Histogram: fix crash on scroll after reset

- data/anselconfig.xml.in
- src/libs/export.c
Because "Same as original" is set as default and is not good.
> Export: Set default color profile to sRGB perceptual

- build.sh
When executing `./build.sh -h`, it was running the quoted code 'git pull' in the --update command description, and the text was not showing.
I replaced the backticks.
> build.sh help : the quoted code piece was actually executed

- data/anselconfig.xml.in
- src/bauhaus/bauhaus.c
- src/bauhaus/bauhaus.h
This lets the user set the timeout value, to prevent the pipeline to recompute while scrolling.
Under Preference > Processing > CPU GPU
> Preferences : New "timeout" setting

- data/anselconfig.xml.in
- src/iop/negadoctor.c
Because it’s handy when you have set up and copied the film settings across all roll scans, and then want to edit only the print tab.
> Negadoctor: remember last selected notebook page

- src/iop/diffuse.c
This PR lets have more flexibility to the `Luminance masking threshold` setting in D&S by adding 2 decimal to the setting.
Setting at `0.0 %`:
Setting at `1.0 %`
Observe the gap at the low values in the scope.
Setting at `0.01 %` with this PR.
Not a big gap in low values.
Top : `1.0 %`
Bottom : `0.01 %`
Thank you.
> D&S : Threshold percent decimal to 2

- src/common/collection.c
- src/common/import.c
This is something I wanted to do since I worked on import.
This code cleverly selects the directory to display, ensuring that the lighttable view moves to the appropriate directory when the first image is imported.
It is configured to also display the contents of all subdirectories within the selected directory.
The scheme is the following:
- If user imports images in place and Collection View mode is on "Tree":
- if the user selected 1 folder in Import's file explorer:
- the lighttable displays the contents of that folder.
- else, the lighttable displays the contents of the folder showing in the file explorer in Import.
- In all other cases (other Collection View mode, images are imported as copies ...), the lighttable displays the first imported image's folder.
All this is done only if …
> Lighttable: show the correct folder / collection on the first image imported

- packaging/macosx/3_make_hb_ansel_package.sh
- packaging/macosx/ansel.bundle
- packaging/macosx/settings.ini
With the last update of either MacOS X or Ansel dependencies provided by Homebrew,
any Ansel built for MacOS X fail to start because either GDK Pixbuf doesn't find the icons for Ansel or it fails to access either its image loaders or the MIME database.
It seems the Darktabke team fixed their build for MacOS X. This PR carries those changes from Darktable so that any Ansel program built for MacOS X can successfully starts.
> Fix Ansel starting failure on MacOS X

- src/common/darktable.c
- src/main.c
This doesn't redirect stdout and stderr stream in a file when `-d` or `--debug` are used so we keep the console open.
> Windows: keep stdout in console when debugging

- src/common/iop_order.c
- src/develop/imageop.c
This doesn't allow the user:
- to move a module being the source of a raster mask ABOVE a module using it,
- to move a module using a raster mask BELOW its module source.
It would be nice if there was something to alert the user on what's happening, like turning the mask button color red in module header of those concerned by the rastermask ...
> IOP order: add raster mask module user/source rules

- src/common/mipmap_cache.c
- `filename_size` renamed to `filename_len` because `size` supposes it includes the null terminating char (as **sizeof()** would do), but **strlen()** doesn't.
- `PATH_MAX` includes null terminating char, so we need to see if the string length will be greater or equal.
- Adding `\0` at the end of strings we are initializing is redundant.
- **g_snprintf()** lets us manipulate string securely, without overflow and always terminate with `\0` even if the source is longer than the target.
> Refactor to satisfy compiler on string manipulation

- src/control/control.c
When (accidentally) double-clicking in certain areas of the darkroom (mainly on the border of the central image),
the view would switch to the Lighttable. This behavior is no longer expected or necessary,
as there is now a home button, a menu entry to open the Lighttable, and a keyboard shortcut for it.
And it gets me on my nerves 😒
> Remove hiddent shortcut to lighttable by double click
