aurelienpierreeng/ansel

po/fr.po

Translation seems good with the new fr.po. I will do a review with my use. I will keep you informed.
Thx
Guillaume

update fr.po with .pot : fix most of translation in french

---

po/fr.po

fix french translation

---

packaging/arch/README

I just have a working PKGBUILD for ansel because I need it.

Update Arch Linux package link

---

po/POTFILES.in
po/ansel.pot
po/zh_CN.po

Because it happens to be my native language :-)
Currently I just added missing translations, checking existing translation is a large project and I may do it when I have time.
This PR also updates `ansel.pot` and `POTFILES.in` to grab newest strings from code. We don't have `data/build/ansel.desktop.in` so I removed it from `POTFILES.in`.

Update zh_CN translation

---

po/ansel.pot
po/zh_CN.po

Just add translation for the newly added "Selected" button, I like it.
Maybe I should gather more translation then PR together, but I am waiting my new lens for a week and not in the mood to do anything else so I just pick some minor work to do 😸️

Update zh cn translation

---

.ci/ci-script-appimage.sh

Should fix the openstreetmap lib problem and make the map view work.

Bundle views dependencies in AppImage

---

src/common/darktable.c
src/common/database.c
src/common/http_server.c
src/generate-cache/main.c
src/gui/gtk.c
src/gui/gtkentry.c
src/imageio/storage/example.c
src/iop/lut3d.c
src/libs/styles.c
src/libs/tagging.c
src/views/darkroom.c
src/views/view.c

Found some 'darktable' labels scattered around souces. Replaced with 'Ansel'

Replaced 'darktable' labels with 'Ansel'

---

src/common/collection.c

Hello,
Please find the fix for the issue #165 .
This corrects the behaviour met by windows users when they try to filter collections by date.
André

fix timestamp issue on windows #165 

---

data/themes/ansel.css
src/develop/blend_gui.c

Make the style of new blending bar consistent, please check the screenshots and commit messages for reasons and details.

Blending: Various style fixes

---

tools/extract_wb_from_images.sh
tools/purge_from_cache.sh
tools/purge_non_existing_images.sh
tools/purge_unused_tags.sh

Changed darktables config/bin/ref into Ansel

Fixed Bash script tools

---

po/ansel.pot
po/zh_CN.po

Some missed corrections I found today.
I am sorry this has to be in another PR, some translations only show when editing non-RAW images so I don't find them previously.

po: Update zh_CN translation

---

po/fr.po
po/it.po

fix issue aurelienpierreeng/ansel#304

---

po/zh_CN.po

Adapt 62a38008b42d42996dfcfb8d79541d50ea863786.

po: Update zh_CN translation to adapt non-ASCII pruning

---

src/develop/pixelpipe_hb.c

Fix GPU memory leak on restarted pixel pipeline

---

src/common/import.c

Small change so we can see the preview of the first found file
in a highlighted folder in the file chooser.

Import: Get preview from first found file

---

src/common/import.c

A variable was freed twice ...

Import: fix crash bug

---

src/control/jobs/control_jobs.c

solves a TODO : `valid way of checking if all chars are 0 ?`

Import: Better way to check on a variable content.

---

src/common/import.c
src/common/variables.c
src/common/variables.h
src/control/jobs/control_jobs.c

Import: fix empty base_directory config value

---

ansel.pot
it.po
po/POTFILES.in

Cancelled two non exixtent files from POTFILES.in
Updated strings in ansel.pot
Updated Italian translation

Updated in translation

---

src/dtgtk/thumbtable.c

Drag & drop : connect to the import job.

---

build.sh

This fix an error "impossible to create simlink" if folder doesn't exist.

Update build.sh : enforce checks on simlink creation

---

src/common/variables.c
src/gui/gtkentry.c

- Added `FOLDER.NAME` as an alternative to `ROLL.NAME` since it doesn't mean anything now,
- Added `ANSEL` as an alternative to `DARKTABLE`.

Variables : some updates

---

src/develop/pixelpipe_hb.c

This avoid segfault in some case when raster masks are not found, and tells the user about it with some hints.
fix #482

Pixelpipe: refactor raster mask a bit + more alert

---

build.sh

Makes the package command working on Windows

Update build.sh script for Windows packaging
